#!/usr/bin/python
#coding:utf-8
i = 0
time = 0
while i <= 3:
    login = raw_input("please input your name: ")
    i += 1
    time = 3 - i
    if login == "reboot":
        passwd = raw_input("please input your passwd: ")
        if time >= 0:
            if passwd == "123456":
                print "欢迎%s，您登录成功!"%(login)
                break
            elif passwd !="123456" and len(passwd)<6:
                print "对不起，密码长度必须大于6位!您还有%s次机会"%time
            else:
                print "对不起，您的密码错误！您还有%s次机会"%time
        else:
            print "您的密码输入错误超过3次，帐号已被锁定!"
    else:
        print "user not is exist!"
        break
