#!/usr/bin/python
# --*-- conding:utf-8 --*--
import sys
try:
name = str(raw_input("Please input youer name:").strip())
  name =  str(name)
except Exception as ex:
   print ("not ok")
   print (ex)
#if name == "chenfei" and name.isalpha():
if name == "chenfei":
   print "Wlecome python world {}".format(name)
elif not name.strip():
   print 'name is null please input check'
else:
    print "The input name is incorrect. Please re-enter it"
   
